USE KODILLA_COURSE;

CREATE VIEW BESTSELLERS_COUNT AS SELECT count(*) AS BESTSELLER_COUNT
FROM BOOKS BK
WHERE BK.BESTSELLER =1 ;

COMMIT;

CREATE EVENT UPDATE_BESTSELLER
ON SCHEDULE EVERY 1 MINUTE
DO 
CALL UpdateBestSellers();
INSERT STATS (STAT_DATE, STAT, VALUE) VALUE (CURDATE(), "BESTSELLERS",(SELECT * FROM bestsellers_count));

COMMIT;