EXPLAIN SELECT * FROM books;
COMMIT;

CREATE INDEX BOOK_IND ON BOOKS (TITLE);
COMMIT;

EXPLAIN SELECT * FROM books;
COMMIT;

EXPLAIN SELECT * FROM readers WHERE FIRSTNAME = "John";
COMMIT;

CREATE INDEX READERS_IND ON readers (FIRSTNAME, LASTNAME);
COMMIT;

EXPLAIN SELECT * FROM readers WHERE FIRSTNAME = "John";
COMMIT;