USE KODILLA_COURSE;

CREATE TABLE STATS (
STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
STAT_DATE DATETIME NOT NULL,
STAT VARCHAR(20) NOT NULL,
VALUE INT(11) NOT NULL
);
COMMIT;

CREATE VIEW BESTSELLERS_COUNT AS SELECT count(*) AS BESTSELLER_COUNT
FROM BOOKS BK
WHERE BK.BESTSELLER =1 ;

COMMIT;
DELIMITER $$
CREATE EVENT UPDATE_BESTSELLER
ON SCHEDULE EVERY 10 SECOND
DO
BEGIN
	CALL UpdateBestSellers();
	INSERT STATS (STAT_DATE, STAT, VALUE) VALUE (CURDATE(), "BESTSELLERS",(SELECT * FROM bestsellers_count));
END $$
COMMIT;